"""Generate the kNN bandwidth-sensitivity LaTeX table for Appendix C.

Reads both:
  results/e3_metrics_phase2_10seeds.json   (C0/C1/C2/C3 lambda x5/C4)
  results/e3_metrics_c3inf.json    (C3-infty hard-blocked OT)

Produces two side-by-side LaTeX tables:
  Table A: A_v_sem_norm at t=1/2 across k in {30, 80, 200}, all couplings
  Table B: max-over-t A_v_sem_norm across same k

Output:
  results/bandwidth_table.tex   (raw LaTeX snippet, to paste into the .tex)

Run:
  python3 build_bandwidth_table.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
RES = HERE.parents[1] / "results"

PHASE2_JSON = RES / "e3_metrics_phase2_10seeds.json"
C3INF_JSON = RES / "e3_metrics_c3inf.json"
OUT_TEX = RES / "bandwidth_table.tex"

# Order to display rows in the table (paper-friendly grouping)
DISPLAY_ORDER = [
    ("C0_independent",            r"C0 independent"),
    ("C1_euclidean_ot",           r"C1 Euclidean OT"),
    ("C2_condition_aware_random", r"C2 cond.-aware random"),
    ("C3_semOT_lam1",             r"$C3@\lambda{=}1$"),
    ("C3_semOT_lam3",             r"$C3@\lambda{=}3$"),
    ("C3_semOT_lam10",            r"$C3@\lambda{=}10$"),
    ("C3_semOT_lam30",            r"$C3@\lambda{=}30$"),
    ("C3_semOT_lam100",           r"$C3@\lambda{=}100$"),
    ("C3inf_blocked_ot",          r"$C3^\infty$ blocked OT"),
    ("C4_geometry_only_ot",       r"C4 geometry-only OT"),
]

K_TO_SHOW = [30, 80, 200]


def load_runs():
    """Load 10-seed phase2 runs. C3inf_blocked_ot is included in
    phase2_10seeds.json directly (10 seeds)."""
    runs_by_coupling = defaultdict(list)
    if not PHASE2_JSON.exists():
        raise FileNotFoundError(f"{PHASE2_JSON.name} not present")
    with open(PHASE2_JSON) as f:
        data = json.load(f)
    for run in data["runs"].values():
        runs_by_coupling[run["name"]].append(run)
    return runs_by_coupling


def reduce_metric(runs, k, reducer):
    """For each seed compute reducer over t for one k, then mean/std over seeds."""
    vals = []
    for r in runs:
        seq = [m["cond_avg"][str(k)]["sem"]["A_v_norm"]
               for m in r["metrics_per_t"]]
        vals.append(reducer(seq))
    arr = np.asarray(vals)
    return float(arr.mean()), float(arr.std(ddof=1) if len(arr) > 1 else 0.0)


def midpoint_value(seq):
    """seq is the list of t-indexed values; T_GRID is linspace(0.05, 0.95, 19),
    so index 9 (10th element) is t=0.5."""
    return seq[9]


def max_over_t(seq):
    return max(seq)


def fmt_pm(m, s):
    return f"${m:.3f}\\pm{s:.3f}$"


def build_table(runs_by_coupling, reducer, label, caption):
    cols = "l" + "r" * len(K_TO_SHOW)
    lines = []
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(rf"\begin{{tabular}}{{{cols}}}")
    lines.append(r"\toprule")
    header = ["Coupling"] + [f"$k{{=}}{k}$" for k in K_TO_SHOW]
    lines.append(" & ".join(header) + r" \\")
    lines.append(r"\midrule")
    for key, display in DISPLAY_ORDER:
        runs = runs_by_coupling.get(key, [])
        if not runs:
            continue
        cells = [display]
        for k in K_TO_SHOW:
            m, s = reduce_metric(runs, k, reducer)
            cells.append(fmt_pm(m, s))
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{label}}}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def main():
    runs_by_coupling = load_runs()
    present = [k for k, _ in DISPLAY_ORDER if k in runs_by_coupling]
    missing = [k for k, _ in DISPLAY_ORDER if k not in runs_by_coupling]
    print(f"  couplings present : {present}")
    print(f"  couplings missing : {missing}")

    table_mid = build_table(
        runs_by_coupling, midpoint_value,
        label="tab:bandwidth-midpoint",
        caption=(r"Bandwidth sensitivity of "
                 r"$\widetilde{\mathcal{A}}_v^S(t{=}1/2|C)$ for E3. "
                 r"Mean $\pm$ sample SD over 10 seeds. "
                 r"Coupling ordering is stable across $k\in\{30,80,200\}$ "
                 r"even though absolute values shift by a few percent."))
    table_max = build_table(
        runs_by_coupling, max_over_t,
        label="tab:bandwidth-maxt",
        caption=(r"Bandwidth sensitivity of "
                 r"$\max_{t}\,\widetilde{\mathcal{A}}_v^S(t|C)$ for E3. "
                 r"Mean $\pm$ sample SD over 10 seeds. "
                 r"Same ordering invariance as Table~\ref{tab:bandwidth-midpoint}."))

    tex = ("% Auto-generated by build_bandwidth_table.py\n"
           "% Source: e3_metrics_phase2_10seeds.json (10 seeds, all couplings)\n\n"
           + table_mid + "\n\n" + table_max + "\n")
    OUT_TEX.write_text(tex)
    print(f"\nWrote {OUT_TEX}")
    print("\n--- preview ---")
    print(tex)


if __name__ == "__main__":
    main()
