"""Generate the LaTeX table for the Sinkhorn appendix subsection.

Reads:
  results/e3_metrics_sinkhorn.json  (3 couplings x 3 epsilons x 3 seeds)
  results/e3_metrics_phase2.json    (Hungarian references)

Writes:
  results/sinkhorn_appendix_table.tex

Columns: mismatch / T_full / A_v_sem(t=1/2|C) / max_t A_v_sem(t|C) /
         H(K|Y_{1/2},C)/log 2.

Run:
  python3 build_sinkhorn_appendix_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
RES = HERE.parents[1] / "results"
SINK_JSON = RES / "e3_metrics_sinkhorn.json"
HUNG_JSON = RES / "e3_metrics_phase2.json"
OUT_TEX = RES / "sinkhorn_appendix_table.tex"

EPS_LIST = [0.03, 0.1, 0.3]
LOG2 = np.log(2.0)

# Order rows in the appendix table
SINK_GROUPS = [
    ("C1_sinkhorn_eps",       r"$C1$ Sinkhorn"),
    ("C3_lam10_sinkhorn_eps", r"$C3@\lambda{=}10$ Sinkhorn"),
    ("C4_sinkhorn_eps",       r"$C4$ Sinkhorn"),
]
HUNG_REFS = [
    ("C1_euclidean_ot",       r"$C1$ Euclidean OT (Hungarian)"),
    ("C3_semOT_lam10",        r"$C3@\lambda{=}10$ (Hungarian)"),
    ("C4_geometry_only_ot",   r"$C4$ geometry-only OT (Hungarian)"),
]


def collect_runs(data, name):
    return [r for r in data["runs"].values() if r["name"] == name]


def aggregate(runs):
    pm = [r["pair_metrics"] for r in runs]
    mm = [p["mismatch_rate"] for p in pm]
    tf = [p["transport_full"] for p in pm]
    # t=0.5 is at index 9 in linspace(0.05, 0.95, 19)
    av_mid = [r["metrics_per_t"][9]["cond_avg"]["80"]["sem"]["A_v_norm"]
              for r in runs]
    av_max = []
    h_mid = []
    for r in runs:
        seq_av = [m["cond_avg"]["80"]["sem"]["A_v_norm"]
                  for m in r["metrics_per_t"]]
        av_max.append(max(seq_av))
        h_mid.append(r["metrics_per_t"][9]["cond_avg"]["80"]["sem"]["H_KY"] / LOG2)

    def stat(xs):
        a = np.asarray(xs)
        return float(a.mean()), float(a.std(ddof=1) if len(a) > 1 else 0.0)

    return {
        "mismatch": stat(mm),
        "tfull":    stat(tf),
        "av_mid":   stat(av_mid),
        "av_max":   stat(av_max),
        "h_mid":    stat(h_mid),
    }


def fmt_pm(stat, digits=3):
    m, s = stat
    return f"${m:.{digits}f}\\pm{s:.{digits}f}$"


def main():
    with open(SINK_JSON) as f:
        sink = json.load(f)
    with open(HUNG_JSON) as f:
        hung = json.load(f)

    rows = []
    for prefix, display in SINK_GROUPS:
        for eps in EPS_LIST:
            key = f"{prefix}{eps:g}"
            runs = collect_runs(sink, key)
            if not runs:
                print(f"  warning: missing {key}")
                continue
            agg = aggregate(runs)
            label = f"{display}, $\\varepsilon{{=}}{eps:g}$"
            rows.append((label, agg))
    rows.append((r"\midrule", None))   # separator before Hungarian refs
    for key, display in HUNG_REFS:
        runs = collect_runs(hung, key)
        if not runs:
            print(f"  warning: missing Hungarian {key}")
            continue
        rows.append((display, aggregate(runs)))

    lines = []
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{lrrrrr}")
    lines.append(r"\toprule")
    lines.append(r"Coupling & mismatch & $T_{\rm full}$ & "
                 r"$\widetilde{\mathcal{A}}_v^S(\tfrac{1}{2}|C)$ & "
                 r"$\max_{t}\widetilde{\mathcal{A}}_v^S(t|C)$ & "
                 r"$H(K_X|Y_{1/2},C)/\log2$ \\")
    lines.append(r"\midrule")
    for label, agg in rows:
        if agg is None:
            lines.append(label)
            continue
        cells = [
            label,
            fmt_pm(agg["mismatch"]),
            f"${agg['tfull'][0]:.2f}\\pm{agg['tfull'][1]:.2f}$",
            fmt_pm(agg["av_mid"]),
            fmt_pm(agg["av_max"]),
            fmt_pm(agg["h_mid"]),
        ]
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{Entropy-regularized Sinkhorn vs Hungarian assignments "
        r"on the E3 conditional mismatch toy. "
        r"All values are mean $\pm$ sample standard deviation over 3 seeds at "
        r"$N{=}20{,}000$, $k{=}80$. The C3 Sinkhorn rows use the same "
        r"$\lambda{=}10$ semantic penalty before per-batch median cost "
        r"rescaling. Hungarian reference rows are reproduced from "
        r"Table~\ref{tab:e3}.}")
    lines.append(r"\label{tab:sinkhorn-appendix}")
    lines.append(r"\end{table}")

    tex = ("% Auto-generated by build_sinkhorn_appendix_table.py\n"
           "% Source: e3_metrics_sinkhorn.json + e3_metrics_phase2.json\n\n"
           + "\n".join(lines) + "\n")
    OUT_TEX.write_text(tex)
    print(f"wrote {OUT_TEX}")
    print("\n--- preview ---")
    print(tex)


if __name__ == "__main__":
    main()
